version: "3"

services:
  ca-mongodb:
    image: mongo:latest
    container_name: ca-mongodb
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_DATABASE=customer_account"
      - "MONGO_INITDB_ROOT_USERNAME=admin"
      - "MONGO_INITDB_ROOT_PASSWORD=smartm2m"
    command: mongod --quiet --logpath /dev/null

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always

  customer-account:
    build:
      context: customer
      dockerfile: Dockerfile
    # image: python:3.8.16-alpine
    container_name: customer-account
    ports:
      - "8000:8000"
    depends_on:
      - ca-mongodb
      - redis
    volumes:
      - ./customer/src:/src
    environment:
      - SECRET_KEY_BASE=secret
      - MONGO_URL=mongodb://admin:smartm2m@localhost:4000/customer_account?authSource=admin
